version: '3'

services:

  spring:
    image: leonardoaii71/spring:dev
    deploy:
      resources:
        limits:
          cpus: "0.1"
      restart_policy:
        condition: on-failure

    environment:
      - SERVER_PORT=8080
    networks:
      - webnetwork

    depends_on:
      - mysqldb

  spring2:
    image: leonardoaii71/spring:dev
    hostname: spring2
    deploy:
      resources:
        limits:
          cpus: "0.1"
      restart_policy:
        condition: on-failure
    depends_on:
      - mysqldb
    environment:
      - SERVER_PORT=8085
    networks:
      - webnetwork



  haproxy:
    image: leonardoaii71/ha-proxy:unstable
    networks:
      - webnetwork
    depends_on:
      - spring
      - spring2

    volumes:
      - /usr/local/etc/haproxy
    ports:
      - "80:80"
      - "32700:32700"

  mysqldb:
    image: mysql:8
    networks:
      - webnetwork
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polls
    ports:
      - 3306:3306

    volumes:
      - mysql_db:/var/lib/mysql

volumes:
  mysql_db:

networks:
  webnetwork:
