version: '3'

services:

  spring:
    image: leonardoaii71/spring:dev
    ports:
      - 8080
    environment:
      - SERVICE_PORTS=8080
      - SERVER_PORT=8080
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
    networks:
      - web

    depends_on:
      - mysqldb


  haproxy:
    image: dockercloud/haproxy:latest
    depends_on:
      - spring
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

  mysqldb:
    image: mysql
    networks:
      - web
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polls
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql

volumes:
  mysql_db:

networks:
  web:
    driver: overlay
